apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd64
spec:
  limits:
    cpu: 1000
  template:
    metadata:
      labels:
        NodeGroupType: amd64
        provisioner: amd64
        type: karpenter
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: ebs-optimized
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: eks.amazonaws.com/instance-cpu
          operator: In
          values:
            - "4"
            - "8"
            - "16"
            - "32"
        - key: eks.amazonaws.com/instance-hypervisor
          operator: In
          values:
            - nitro
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values:
            - "4"
      taints:
        - effect: NoSchedule
          key: amd64
