---
apiVersion: v1
kind: Pod
metadata:
  labels:
    blog: wireguard
    name: server
  name: server
spec:
  containers:
    - image: nginx
      name: server
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          blog: wireguard
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 80
  selector:
    name: server
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    blog: wireguard
    name: client
  name: client
spec:
  containers:
    - command:
        - watch
        - wget
        - server
      image: busybox
      name: client
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          blog: wireguard
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
---

