apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        kmsKeyID: '{{ .Values.ec2nodeclass.blockDeviceMappings.ebs.kmsKeyID }}'
        volumeSize: 4Gi
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        encrypted: true
        kmsKeyID: '{{ .Values.ec2nodeclass.blockDeviceMappings.ebs.kmsKeyID }}'
        volumeSize: 20Gi
  role: #{{- toYaml .Values.ec2nodeclass.role | nindent 4 }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: '{{ .Values.ec2nodeclass.securityGroupSelectorTerms.tags }}'
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: '{{ .Values.ec2nodeclass.subnetSelectorTerms.tags }}'
  tags:
    karpenter.sh/discovery: '{{ .Values.ec2nodeclass.tags }}'
