concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  validate:
    # temp disable via 'if'
    if: startsWith(github.head_ref, 'opentofu/')
    runs-on: ubuntu-latest
    steps:
      - uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4 # v2.0.1
        with:
          tofu_version: 1.12.2 # renovate: datasource=github-releases depName=opentofu/opentofu packageName=opentofu/opentofu
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false
      - name: Apply terraform fmt and find unformatted files
        run: |
          bash -ex .github/opentofu-fmt.sh
          bash -ex .github/opentofu-validate.sh
    timeout-minutes: 20
name: opentofu-checks
on:
  pull_request:
    paths:
      - .github/opentofu-fmt.sh
      - .github/opentofu-validate.sh
      - .github/tf.sh
      - .github/workflows/opentofu-checks.yml
      - '**.otf'
      - '**.tf'
